FROM nginx


### Change user to perform privileged actions
### USER 0
### Install 'vim'
### RUN install_packages vim
### Revert to the original non-root user
### USER 1001

### Modify 'worker_connections' on NGINX config file to '512'
### RUN sed -i -r "s#(\s+worker_connections\s+)[0-9]+;#\1512;#" /opt/bitnami/nginx/conf/nginx.conf
# Remove the sed command which is fragile
# RUN sed -i '/index\|index\.html\|index\.htm/a     try_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.conf

# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

### Modify the ports used by NGINX by default
### ENV NGINX_HTTP_PORT_NUMBER=8181 ## It is also possible to change this environment variable at runtime
### EXPOSE 8181 8143

### Modify the default containers user
### USER 1002

ARG REPO

COPY apps/${REPO}/dist /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx","-g","daemon off;"]



