import WebAppLayout from "@/layouts/Webapp/WebAppLayout";
import { ReactNode } from "react";

// export type Props = {
//     children: ReactNode;
//     params: { locale: string };
// };

// const inter = Inter({subsets: ["latin"]});
//
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function PageLayout({ children }: Readonly<{ children: ReactNode }>) {
    return <WebAppLayout>{children}</WebAppLayout>;
}
