import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {colorBgPrimary, ThemeProvider} from "@/providers/theme";
import AppRootLayout from "@/layouts/AppRootLayout";
import {NextIntlClientProvider} from "next-intl";
import {ReactNode} from "react";
import {getMessages} from "next-intl/server";
import {locales} from "@/i18n/routing";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: process.env.NEXT_PUBLIC_APP_NAME,
    // description: "Generated by create next app",
};

export function generateStaticParams() {
    return locales.map((locale) => ({locale}));
}

export default async function RootLayout({children, params: {locale}}: Readonly<{
    children: ReactNode;
    params: { locale: string };
}>) {

    return (
        <html lang="en">
        <body className={`${inter.className}`}
              style={{margin: 0, background: colorBgPrimary}}>
        <NextIntlClientProvider messages={await getMessages()}>
            <ThemeProvider>
                <AppRootLayout>
                    {children}
                </AppRootLayout>
            </ThemeProvider>
        </NextIntlClientProvider>
        </body>
        </html>

    );
}
