"use client";
import React from "react";
import Footer from "@/components/Footer";
import { Flex } from "antd";
import Logo from "@/components/Logo";

export default function Privacy() {
    return (
        <>
            <Flex style={{ paddingInline: 30, paddingBlock: 10 }}>
                <Logo />
            </Flex>
            <div className="legal-container">
                <div className="content-block">
                    <div className="title">Privacy Policy</div>
                    <div className="time">Last Updated: 2023-08-01</div>
                    <p>
                        Welcome to the Privacy Policy for the XTips Chrome extension (hereinafter referred to as
                        "XTips", "we", "us", or "our"). We understand the importance of your privacy, and we are
                        committed to protecting your personal information. This Privacy Policy outlines the types of
                        information we collect, how we use it, and the measures we take to protect your data.
                    </p>
                    <p>
                        By using the XTips Chrome extension, you acknowledge and agree to the terms and conditions of
                        this Privacy Policy. If you do not agree with any part of this Privacy Policy, please do not use
                        or install the XTips Chrome extension.
                    </p>
                </div>
                <div className="content-block">
                    <div className="font-bold text-2xl">Information We Do Not Collect</div>
                    <div className="font-bold text-xl">Personal Information</div>
                    <p>
                        We take your privacy seriously and only collect your email and name to identify you when you log
                        in, helping to sync your settings across different browsers and devices. Other than that, we do
                        not collect any other personal information. The XTips Chrome extension operates without
                        requiring any additional personal data from you, and we do not store such information.
                    </p>
                </div>
                <div className="content-block">
                    <div className="font-bold text-2xl">Information We Collect</div>
                    <div className="font-bold text-xl">Chrome Extension Automatically Generated Reports</div>
                    <p>
                        One of the types of information we collect from users is the Chrome extension automatically
                        generated report. This information is used for the sole purpose of improving the functionality
                        of the XTips Chrome extension and understanding the usage patterns of our users. The collected
                        data may include technical information such as browser version, extension version, and operating
                        system.
                    </p>
                    <div className="font-bold text-xl">Google Analytics</div>
                    <p>
                        The second type of information we collect is default information about user interactions with
                        the XTips Chrome extension through the use of Google Analytics, a web analytics service provided
                        by Google Inc. ("Google"). Google Analytics uses cookies to help us analyze how users use the
                        extension. The information generated by the cookies about your use of the extension (including
                        your IP address) will be transmitted to and stored by Google on servers in the United States.
                    </p>
                </div>
                <div className="content-block">
                    <div className="font-bold text-2xl">How we use your information</div>
                    <p>
                        We use the information we collect, including Chrome extension automatically generated reports
                        and Google Analytics data, to:
                    </p>
                    <p>1) Improve the XTips Chrome extension's functionality.</p>
                    <p>2) Analyze usage patterns to better understand user preferences.</p>
                    <p>3) Identify and troubleshoot issues with the Chrome extension.</p>
                    <p>4) Improve the overall user experience.</p>
                </div>
                <div className="content-block">
                    <div className="font-bold text-2xl">Information Security</div>
                    <p>
                        We take appropriate measures to protect the limited information we collect from unauthorized
                        access, disclosure, alteration, or destruction. We follow industry-standard practices to ensure
                        the security of the data we manage.
                    </p>
                </div>
                <div className="content-block">
                    <div className="font-bold text-2xl">Marketing and advertising</div>
                    <p>
                        Where required by law we will only send you marketing information, including sending you updates
                        and information about our new products and services, upcoming events or other promotions or
                        news, including by email or push notification, as permitted by law. You may opt-out of receiving
                        such emails by following the instructions in each promotional email we send you or by updating
                        your user settings. In addition, if at any time you wish not to receive future communications or
                        you wish to have your name deleted from our mailing lists, please contact us at
                        <a href="mailto:service@xtips.ai">service@xtips.ai</a> We will continue to contact you via email
                        regarding the provision of our Services and to respond to your requests.
                    </p>
                </div>
                <div className="content-block">
                    <div className="font-bold text-2xl">Changes to the Privacy Policy</div>
                    <p>
                        We may update our Privacy Policy from time to time. Any changes to this Privacy Policy will be
                        posted on this page, and the "Last Updated" date at the top will be revised accordingly. Your
                        continued use of the XTips Chrome extension after any changes to the Privacy Policy constitutes
                        your acceptance of the updated policy.
                    </p>
                </div>
                <div className="content-block">
                    <div className="font-bold text-2xl">Contact Us</div>
                    <p>
                        If you have any questions or concerns about our Privacy Policy, please feel free to contact us
                        at
                        <a href="mailto:service@xtips.ai">service@xtips.ai</a>
                    </p>
                </div>
            </div>
            {/* <Footer/> */}
        </>
    );
}
